version: '3.8'

services:
  # Servicio para producción
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gymswipe-frontend-prod
    ports:
      - "80:80"
    restart: unless-stopped
